project:
  type: website

website:
  title: "OSU Code Club"
  navbar:
    left: 
      - href: pages/schedule.qmd
        text: Schedule
      - href: pages/previous.qmd
        text: Previous sessions
      - text: New here?
        menu:
        - text: Computer setup for Code Club
          href: pages/setup.qmd
        - text: R resources for beginners
          href: pages/r_resources.qmd
        - text: Sign up!
          href: https://forms.gle/eYkMvmJShrcANUrt5
    right:
      - text: About
        href: about.qmd
      - icon: github
        href: https://github.com/osu-codeclub/osu-codeclub.github.io
format:
  html:
    theme: flatly
    css: styles.css
