project:
  type: website
  preview: 
    navigate: false

website:
  title: "OSU Code Club"
  site-url: https://osu-codeclub.github.io/
  repo-url: https://github.com/osu-codeclub/osu-codeclub.github.io
  repo-actions: [edit, issue]
  favicon: "img/codeclub_favicon_cc.jpg"
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    logo: "img/codeclub_favicon.png"
    left:
      - href: pages/schedule.qmd
        text: Schedule
      - href: pages/previous.qmd
        text: Previous sessions
      - text: More resources
        menu:
          - text: Computer setup (installations) for Code Club
            href: pages/setup.qmd
          - text: Other coding-related OSU activities
            href: pages/other.qmd
          - text: ------------------
          - text: Material of an R for beginners workshop (Feb '25)
            href: https://osu-codeclub.github.io/carpentries-feb-2025/
          - text: Material of an R for beginners workshop (Aug '25)
            href: https://osu-codeclub.github.io/carpentries-aug-2025/            
    right:
      - text: Sign up!
        href: https://forms.gle/eYkMvmJShrcANUrt5
      - text: About
        href: about.qmd
      - icon: rss
        href: index.xml
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/osu-codeclub/osu-codeclub.github.io
          - text: Report an Issue
            url:  https://github.com/osu-codeclub/osu-codeclub.github.io/issues/new
format:
  html:
    highlight-style: atom-one
    theme: [flatly, theme_mod.scss]
    css: styles.css
    toc: true
    number-sections: true
    number-depth: 3
    grid:
      body-width: 850px
