---
title: "About OSU Code Club"
about:
  template: solana
  links:
    - icon: github
      text: Github
      href: https://github.com
---

OSU Code Club is a regularly occurring, interactive, online and in-person gathering
to improve coding skills.
We aim for a supportive and fun culture of learning together,
and hope to offer something to participants at any experience level.

Teaching materials for each Code Club are added to this website and will continue
to be available.

Code Club has run since the fall of 2020,
and materials for the 71 sessions in the semesters prior to autum 2023 are
currently available at https://biodash.github.io but will eventually be migrated
to this website.
By popular demand,
Code Club has so far focused entirely on **the R language** and its surrounding
ecosystem (R Markdown, Shiny, etc).

The fall semester of 2023 will ...

If you have any suggestions or requests, ...

### Organizers

The current organizers of Code Club are ...

In previous semesters we also had Michael Broe, Mike Sovic, Stephen Opiyo...

### Learn more about -and get ready for- Code Club

[Form to sign up](https://forms.office.com/r/SgmdwJXEXx)

[Schedule with upcoming session](./pages/schedule.qmd)

[Computer setup instructions](./pages/setup.qmd)

[Resources and tips for R novices](./pages/r_resources.qmd)

[List of previous sessions by semester for AU20-SP23](./pages/previous.qmd)
