---
title: "Other OSU coding-related activities in AU25"
author:
  - Jelmer Poelstra
  - Horacio Lopez-Nicora
  - Jessica Cooperstone
date: 2025-07-24
number-sections: false
title-block-banner: false
---

------------------------------------------------------------------------

<br>

We created a [separate post for the "R for Reproducibility Workshop" in August 2025](../ZZ_2025-08_workshop).
Here, we would like to highlight several other coding-related activities at
OSU in AU25:

------

### Workshop: Version Control with Git

*Fri August 15, 9 am – 3 pm, online via Zoom (free and open to anyone at OSU)*

An introduction to version control with Git and code sharing with GitHub.
This recurring [Carpentries](https://carpentries.org/ "https://carpentries.org/") workshop
is organized for the third time by Research Commons, the Imageomics Institute, and OSU Code Club.
[Register here](https://library.osu.edu/events/version-control-with-git-virtual-event-1 "https://library.osu.edu/events/version-control-with-git-virtual-event-1").

------

### Course: Data visualization in R

*AU25 HCS 7100, Tue 4:10-5:55 pm, in person and online, 2 credits, instructor: Jessica Cooperstone*

This course aims to introduce students to the principles and practice of data visualization.
Students will learn fundamental principles of data visualization and create figures
that appropriately and ethically represent their data.
Data visualizations will be created in the R programming environment,
using tools including the grammar of graphics implemented in ggplot2.
In the process of creating visualizations,
students will also become familiar with data handling and wrangling in R.

------

### Courses: Practical Computing Skills for Omics Data (AU25) and Genome Analytics (SP26)

*AU25 PLNTPTH 5006, Tue/Thu 12:45-2:05 pm, online, 3 credits, instructor: Jelmer Poelstra*  
*SP26 HCS 7004, 4 credits, instructor: Jonathan Fresnedo-Ramirez*

Practical Computing Skills for Omics Data teaches foundational skills to work with large omics data sets,
focusing on coding and reproducibility in research.
Students will learn to document, organize, and share their research;
work in the Unix shell and at the Ohio Supercomputer Center;
write shell scripts and use containers to run bioinformatics programs;
use version control with Git and GitHub;
use R to process and visualize data;
write automated pipelines with Nextflow;
and use generative AI to help them code.
Students are encouraged to complement this course in SP26 with **Genome Analytics** 
that offers in-depth treatments of a variety of omics data analyses that these
computing skills can be applied to.
