---
title: "Related resources and activities"
toc: true
number-sections: false
date-modified: 2026-02-14
---

------

<hr style="height:1pt; visibility:hidden;" />

On this page, we're listing other coding-related activities at OSU that
Code Clubbers may be interested in.
[Let us know](/about.qmd#organizers) if you have a suggestion of something
to add here.

<hr style="height:1pt; visibility:hidden;" />

## Formal classes

- [**PLNTPTH 5006: Practical Computing Skills for Omics Data**](https://mcic-osu.github.io/pracs-au25/) --
  taught each Autumn by Jelmer
- [**HCS 7100: Data Visualization in R**](https://www.rdataviz.com/) -- taught each Autumn by Jess
- **ENT 6702: Entomological Techniques and Data Analysis** --
  taught by Kayla Perry and Sam Ward, uses R

<hr style="height:1pt; visibility:hidden;" />

## Other

_None currently!_

<hr style="height:1pt; visibility:hidden;" />

## Online material of past workshops

- OSU Carpentries workshop organized by Code Club, Research Commons, and Imageomics
  on [R for Reproducible Research](https://osu-codeclub.github.io/carpentries-feb-2026/)
  (Feb 2026)

- [Amplicon Metabarcoding Workshop](https://jelmerp.github.io/metabar-ws24/)
  (Mar 2024)

<hr style="height:1pt; visibility:hidden;" />

## Outside of OSU

### Online resources (free)

- **Carpentries**
  - [Library Carpentry Lessons](https://librarycarpentry.org/lessons/)
  - [Data Carpentry Lessons](https://datacarpentry.org/lessons/)
  - [Software Carpentry Lessons](https://software-carpentry.org/lessons/)

### Online courses (paid)

- [Visualize your Science](https://www.visualizeyourscience.com/course-vys)
- [Canadian Bioinformatics Workshops](https://bioinformaticsdotca.github.io/)
- [Physalia Workshops and Courses](https://www.physalia-courses.org/courses-workshops/)

