---
title: "Schedule for Code Club"
date-modified: 2023-12-18
---

<br>

In the spring of 2024, we will be meeting on **Fridays from 12-1pm**. Join us:

* in person in Columbus (**Howlett 340** with Jessica Cooperstone and Horacio Lopez-Nicora)  
* in Wooster (**location TBD** with Jelmer Poelstra)  
* through **Zoom** ([sign up](https://forms.gle/eYkMvmJShrcANUrt5) to receive the Zoom link)

<br>

In the fall of 2023, we are meeting on **Mondays from 4-5 pm**.

Join us in person in Columbus (**Howlett 340** with Jessica Cooperstone)
or in Wooster (**Selby 203** with Jelmer Poelstra),
or connect through **Zoom**
([sign up](https://forms.gle/eYkMvmJShrcANUrt5) to receive the Zoom link).

<br>

| Session | Date    | Presenter         | Link                                                                              |
|---------|---------|-------------------|-----------------------------------------------------------------------------------|
| S06E01  | Aug 28  | Jess              | [Quarto website 1: **Initiating a website**](/posts/website_01_initiation/)       |
| S06E02  | Sep 11  | Jelmer            | [Quarto website 2: **Adding a page & YAML formatting**](/posts/website_02/)       |
| S06E03  | Sep 18  | Jess              | [Quarto website 3: **Deploying to GitHub**](/posts/website_03_deploy-github/)     |
| S06E04  | Sep 25  | Jelmer            | [Quarto website 4: **Interacting with your repository**](/posts/website_04/)      |
| S06E05  | Oct 2   | Jess              | [Quarto website 5: **Modifying your site**](/posts/website_05)                    |
| S06E06  | Oct 9   | Jelmer            | [Quarto website 6: **Quarto features**](/posts/website_06)                        |
| S06E07  | Oct 16  | Jess              | [Quarto website 7: **Quarto presentations** ](/posts/website_07_presentation)     |
| S06E08  | Oct 30  | Horacio           | [Shiny App 01: **Intro to Shiny** ](/posts/shiny_01)                              |
| S06E09  | Nov 06  | Horacio           | [Shiny App 02: **Intro to Shiny (cont.)** ](/posts/shiny_02)                      |
| S06E10  | Nov 13  | Horacio & Sandip  | [Shiny App 03: **Map viz. in Shiny** ](/posts/shiny_03)                           |
| S06E10  | Dec 04  | Horacio           | [Shiny App 04: **Deploying our Shiny App** ](/posts/shiny_04)                     |